name: Build

on:
  push:
    branches:
      - 'main'
      - 'rr/**' # "rr" stands for "remote run"
      - 'bobko/**'
    tags:
      - '*'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md
        os: [macos-13, macos-14, macos-15]
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .deps
          key: ${{ matrix.os }}-${{ runner.arch }}-${{ hashFiles('script/install-dep.sh', 'Gemfile', '.bundle/config') }}
      - uses: nikitabobko/setup-swift@21e0b6448e6aa76937c51d4b172f6cba5e537cde # todo migrate to swiftly
        with:
          swift-version: '6.1.0'
      - run: |
          if sw_vers -productVersion | grep -q "^13"; then # macOS 13
            true
          else
            sudo xcode-select -s "$XCODE_16_DEVELOPER_DIR" # Affects macOS SDK
          fi
      - run: brew install bash fish xcbeautify
      - run: env # Debug
      - run: ./script/install-dep.sh --all
      - run: ./build-debug.sh
      - run: ./run-tests.sh
      - name: Check macOS version
        id: check_macos
        run: |
          sw_vers -productVersion
          if sw_vers -productVersion | grep -q "^15"; then
            echo "is_macos_15=true" >> $GITHUB_OUTPUT
          else
            echo "is_macos_15=false" >> $GITHUB_OUTPUT
          fi
      - name: Install the Apple certificate and provisioning profile
        if: steps.check_macos.outputs.is_macos_15 == 'true'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          
      - name: Run build-release.sh and install-from-sources.sh on macOS 15
        if: steps.check_macos.outputs.is_macos_15 == 'true'
        run: |
          ./build-release.sh --codesign-identity "Apple Development: Alexander Gartner (QJMXJPV5B7)"
          ./install-from-sources.sh --dont-rebuild

      - name: Get zip path
        id: zip_path
        if: steps.check_macos.outputs.is_macos_15 == 'true'
        run: echo "zip_path=$(ls .release/*.zip)" >> $GITHUB_OUTPUT

      - name: Upload build results
        if: steps.check_macos.outputs.is_macos_15 == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ steps.zip_path.outputs.zip_path }}

      - name: Create Release
        if: steps.check_macos.outputs.is_macos_15 == 'true' && github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.zip_path.outputs.zip_path }}
          draft: false
          prerelease: false
